"""empty message

Revision ID: 2994bd2283b0
Revises: 53db5d04eb54
Create Date: 2022-06-21 17:07:46.125798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2994bd2283b0'
down_revision = '53db5d04eb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_table_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_table_num')
    # ### end Alembic commands ###
