"""empty message

Revision ID: 53db5d04eb54
Revises: 
Create Date: 2022-06-21 17:05:05.761883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53db5d04eb54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.Column('price_dollars', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
