"""empty message

Revision ID: fd066ff70050
Revises: 2994bd2283b0
Create Date: 2022-06-22 03:54:12.711632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd066ff70050'
down_revision = '2994bd2283b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_num', sa.Integer(), nullable=False))
    op.alter_column('orders', 'price_rub', type=sa.Float())
    op.alter_column('orders', 'price_dollars', type=sa.Float())
    op.alter_column('orders', 'price_dollars', new_column_name='price_usd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_num')
    op.alter_column('orders', 'price_usd', new_column_name='price_dollars')
    op.alter_column('orders', 'price_rub', type=sa.Integer())
    op.alter_column('orders', 'price_dollars', type=sa.Integer())
    # ### end Alembic commands ###
